
name: PyEmbla CI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install package dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools pytest
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Slack notification
      uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: Integration Testing
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: failure() # Pick up event if the job fails
